"L_Hip" :"thigh_l",
"L_Knee":"calf_l",
"L_Ankle": "foot_l",
"L_Toe": "ball_l",
"R_Hip" :"thigh_r",
"R_Knee":"calf_r",
"R_Ankle":  "foot_r",,
"R_Toe", "ball_r",
"Torso":  "spine_01",
"Spine": "spine_02",
"Chest":  "spine_03",
"Neck": "neck_01",
"Head": "head",
"L_Thorax": "clavicle_l",
"L_Shoulder": "upperarm_l",
"L_Elbow": "lowerarm_l",
"L_Wrist": "hnad_l",
"L_Hand", "hh1"
"R_Thorax":  "clavicle_r",
"R_Shoulder": "upperarm_r",
"R_Elbow":  "lowerarm_r",
"R_Wrist":  "hnad_r",,
"R_Hand":"hh2"